baseURL = 'https://mothbe.github.io/'
copyright = "© 2024 Tech Notes. All rights reserved"
languageCode = 'en-us'
title = 'Tech Notes'
theme = "hugo-flex"
paginate = 8

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"
    weight = 3
  [[menu.main]]
    identifier = "rss"
    name = "RSS"
    url = "/feed.xml"
    weight = 4
     [[menu.main.params]]
     format = "rss" 
 [[menu.main]]
    identifier = "categories"
    name = "Categories"
    url = "/categories"
    weight = 5
#  [[menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about/"
#    weight = 3

[outputs]
home = ["HTML", "RSS"]
page = ["HTML", "RSS"]

[outputFormats.RSS]
mediatype = "application/rss+xml"
baseName = "feed"