baseURL = "https://mothbe.github.io"
languageCode = "en-us"
title = "Tech Notes"
theme="archie"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
	mode="toggle"
	#featherIconsCDN=true
	#subtitle = "Follow the one who follows the white rabbit"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/mothbe"

[[params.social]]
name = "Bitbucket"
icon = "bitbucket"
url = "https://bitbucket.com/mothbe"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

#[[menu.main]]
#name = "About"
#url = "/about"
#weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4